iterations:
- name: try_rates
  params:
    param_values: [0.1, 0.1, 0.0, 0.0]
  init_state_values: [0.1, 0.1, 0.0, 0.0]
  seed: 0
  state_width: 4
  state_history_depth: 1
- name: score_events
  params: {}
  params_from_upstream:
    rates:
      upstream: 0
  init_state_values: [0.0, 0.0, 0.0, 0.0]
  seed: 42
  state_width: 4
  state_history_depth: 2
- name: conversion_events
  params:
    conversion_probs: [0.7, 0.7]
    score_events_partition: [1]
  params_from_upstream:
    try_values:
      upstream: 1
  init_state_values: [0.0, 0.0]
  seed: 43
  state_width: 2
  state_history_depth: 1
init_time_value: 0.0
timesteps_history_depth: 2
